export const ITEMS = [
  {
    id: 0,
    title: "paperlessinvites",
    name: "paperlessinvites",
    para: "Digital invitations web App",
    git: "https://github.com/Sankalp-2003/paperlessinvites",
    link: "https://paperlessinvites.in/",
    img: "/paperlessInvites.png",
    desc: ` Developed paperlessinvites.in from scratch, creating 40+ dynamic digital invitation pages using HTML, SCSS, and TypeScript, allowing users to personalize details likenames and dates. Implemented Angular components, reactive forms, and form validation to create modular, user-friendly interfaces, ensuring seamless interaction and data integrity. Managed routing for smooth navigation and integrated logic for dynamic content generation based on user input. Collaborated in an agile environment, using Git for version control, contributing to daily stand-ups, and participating in sprint planning`,
    icons: {
      js: false,
      ts: true,
      angular: true,
      react: false,
      html: true,
      css: false,
      tailwind: false,
      scss: true,
    },
  },
  {
    id: 1,
    title: "FilmyVerse",
    name: "FilmyVerse",
    para: "Responsive movie app using Firebase.",
    git: "https://github.com/Sankalp-2003/filmyVerse",
    link: "https://filmyverse-sankalp-2003.netlify.app/",
    img: "/Filmyverse.png",
    desc: ` A fully responsive React-based web application designed for movie enthusiasts to explore, add, and review films. Leveraging Firebase as a real-time database, users can seamlessly add new movies, complete with titles, images, and descriptions, which are dynamically displayed on the homepage. The platform also allows users to write and submit reviews, with both the reviews and comments stored and managed in Firebase. This project showcases my expertise in React, state management, real-time data handling with Firebase, and creating intuitive, user-friendly interfaces.`,
    icons: {
      js: true,
      ts: false,
      angular: false,
      react: true,
      html: true,
      css: false,
      tailwind: true,
      scss: false,
    },
  },
  {
    id: 2,
    title: "E-Shop",
    name: "E-Shop",
    para: "Responsive eCommerce site with React and Redux.",
    git: "https://github.com/Sankalp-2003/E-Shop",
    link: "https://e-shop-sankalp-2003.netlify.app/",
    img: "/E-commerce.png",
    desc: ` A fully responsive eCommerce platform built using React, Redux Toolkit, and Tailwind CSS for a seamless and intuitive user experience across all devices. The site features a Home Page with a Hero section, categorized products, and top picks. Key functionalities include a dynamic Cart Page with an order summary and smooth checkout flow, integrated billing, shipping, and payment interfaces, as well as order confirmation and tracking options. Additionally, the platform supports product search and filtering. This project showcases my skills in React, Redux Toolkit for state management, and responsive design using Tailwind CSS.`,
    icons: {
      js: true,
      ts: false,
      angular: false,
      react: true,
      html: true,
      css: false,
      tailwind: true,
      scss: false,
    },
  },
  {
    id: 3,
    title: "Google Gemini-clone",
    name: "Gemini",
    para: " Responsive AI app with Google Gemini API.",
    git: "https://github.com/Sankalp-2003/Gemini-Clone",
    link: "https://gemini-sankalp-2003.netlify.app/",
    img: "/Gemini.png",
    desc: ` A responsive Generative AI application built with React.js, leveraging the Google Gemini API to replicate the functionality of Google Gemini. This AI app allows users to interact with generative models for various use cases, demonstrating the power of real-time AI integration. The project showcases my proficiency in React.js, API integration, and building responsive, AI-powered applications.`,
    icons: {
      js: true,
      ts: false,
      angular: false,
      react: true,
      html: true,
      css: true,
      tailwind: false,
      scss: false,
    },
  },
  {
    id: 4,
    title: "Ochi Design",
    name: "Ochi",
    para: "Responsive React site with smooth animations.",
    git: "https://github.com/Sankalp-2003/Ochi",
    link: "https://ochi-sankalp-2003.netlify.app/",
    img: "/Ochi.png",
    desc: ` A pixel-perfect recreation of the award-winning Ochi Design website, developed using React.js with mobile responsiveness. This project replicates the unique animation effects and design elements, utilizing Framer Motion for seamless animations and Locomotive Scroll for smooth scrolling with dynamic page speed control. A standout feature includes an interactive "eye" component that tracks the cursor’s movement for enhanced user engagement. This project highlights my expertise in React.js, animation libraries like Framer Motion, and creating immersive, interactive web experiences.`,
    icons: {
      js: true,
      ts: false,
      angular: false,
      react: true,
      html: true,
      css: false,
      tailwind: true,
      scss: false,
      gsap: true,
      motion: true,
    },
  },
  {
    id: 5,
    title: "VirtualR",
    name: "VirtualR",
    para: "Modern React site with Tailwind CSS.",
    git: "https://github.com/Sankalp-2003/VirtualR",
    link: "https://virtualr-sankalp-2003.netlify.app/",
    img: "/VirtualR.png",
    desc: ` A modern, fully responsive website built from scratch using React and Tailwind CSS. The site features a sleek, responsive Navbar with a mobile drawer for easy navigation. It includes a visually striking Hero section with gradient text, providing a modern aesthetic. Integrated video elements play on autoplay and loop to enhance user engagement. The site also features a clean UI for displaying product features, a pricing card section offering three plans, as well as testimonials and a footer—all styled using Tailwind CSS. This project demonstrates my skills in responsive design, React development, and creating modern, user-friendly interfaces with Tailwind CSS.`,
    icons: {
      js: true,
      ts: false,
      angular: false,
      react: true,
      html: true,
      css: false,
      tailwind: true,
      scss: false,
    },
  },
  {
    id: 6,
    title: "Printify",
    name: "Printify",
    para: "Responsive React app inspired by Printify, with animations and interactivity.",
    git: "https://github.com/Sankalp-2003/Printify",
    link: "https://printify-sankalp.netlify.app/",
    img: "/printify.png",
    desc: ` Developed a responsive React web application inspired by the Printify homepage. Utilized SCSS for styling to create a clean and modern design. Implemented Framer Motion for animations and Swiper JS for interactive content, ensuring an engaging user experience across desktop and mobile devices.`,
    icons: {
      js: true,
      ts: false,
      angular: false,
      react: true,
      html: true,
      css: false,
      tailwind: false,
      scss: true,
    },
  },
];
