export const ITEMS = [
  {
    id: 0,
    title: "Rabbit",
    name: "Rabbit",
    para: "E-commerce app with secure, scalable features.",
    git: "https://github.com/Sankalp-2003/Rabbit",
    link: "https://rabbit-ko9q.vercel.app/",
    img: "/Rabbit.png",
    desc: `Rabbit is a fully functional E-commerce Web Application built using the MERN stack (MongoDB, Express, React, Node.js). It incorporates modern technologies such as Redux Toolkit, Tailwind CSS, Cloudinary, and JWT authentication to deliver a real-world, scalable shopping experience.`,
    icons: [
      "icons/reactIcon.png",
      "icons/tailwindIcon.png",
      "icons/nodejsIcon.png",
      "icons/expressIcon.png",
      "icons/mongodbIcon.png",
    ],
  },
  {
    id: 1,
    title: "Car Rental",
    name: "Car Rental",
    para: "Car rental app with booking and admin features.",
    git: "https://github.com/Sankalp-2003/Car-Rental",
    link: "https://car-rental-peach-ten.vercel.app/",
    img: "/car-rental.png",
    desc: `CarRental is a full-stack Car Rental Booking App built using the MERN Stack. This project features user-friendly car listing and booking functionalities, secure authentication, and a robust admin panel for managing bookings and vehicles. It is designed to be scalable, responsive, and production-ready.`,
    icons: [
      "icons/reactIcon.png",
      "icons/tailwindIcon.png",
      "icons/nodejsIcon.png",
      "icons/expressIcon.png",
      "icons/mongodbIcon.png",
    ],
  },
  {
    id: 2,
    title: "paperlessinvites",
    name: "paperlessinvites",
    para: "Digital invitations web App",
    git: "https://github.com/Sankalp-2003/paperlessinvites",
    link: "https://paperlessinvites.in/",
    img: "/paperlessInvites.png",
    desc: ` Developed paperlessinvites.in from scratch, creating 40+ dynamic digital invitation pages using HTML, SCSS, and TypeScript, allowing users to personalize details likenames and dates. Implemented Angular components, reactive forms, and form validation to create modular, user-friendly interfaces, ensuring seamless interaction and data integrity. Managed routing for smooth navigation and integrated logic for dynamic content generation based on user input. Collaborated in an agile environment, using Git for version control, contributing to daily stand-ups, and participating in sprint planning`,
    icons: ["icons/angularIcon.png", "icons/sassIcon.png"],
  },
  {
    id: 3,
    title: "FilmyVerse",
    name: "FilmyVerse",
    para: "Responsive movie app using Firebase.",
    git: "https://github.com/Sankalp-2003/filmyVerse",
    link: "https://filmyverse-sankalp-2003.netlify.app/",
    img: "/Filmyverse.png",
    desc: ` A fully responsive React-based web application designed for movie enthusiasts to explore, add, and review films. Leveraging Firebase as a real-time database, users can seamlessly add new movies, complete with titles, images, and descriptions, which are dynamically displayed on the homepage. The platform also allows users to write and submit reviews, with both the reviews and comments stored and managed in Firebase. This project showcases my expertise in React, state management, real-time data handling with Firebase, and creating intuitive, user-friendly interfaces.`,
    icons: [
      "icons/reactIcon.png",
      "icons/tailwindIcon.png",
      "icons/firebaseIcon.png",
    ],
  },
  {
    id: 4,
    title: "Google Gemini-clone",
    name: "Gemini",
    para: " Responsive AI app with Google Gemini API.",
    git: "https://github.com/Sankalp-2003/Gemini-Clone",
    link: "https://gemini-sankalp-2003.netlify.app/",
    img: "/Gemini.png",
    desc: ` A responsive Generative AI application built with React.js, leveraging the Google Gemini API to replicate the functionality of Google Gemini. This AI app allows users to interact with generative models for various use cases, demonstrating the power of real-time AI integration. The project showcases my proficiency in React.js, API integration, and building responsive, AI-powered applications.`,
    icons: ["icons/reactIcon.png", "icons/cssIcon.png"],
  },
  {
    id: 5,
    title: "Ochi Design",
    name: "Ochi",
    para: "Responsive React site with smooth animations.",
    git: "https://github.com/Sankalp-2003/Ochi",
    link: "https://ochi-sankalp-2003.netlify.app/",
    img: "/Ochi.png",
    desc: ` A pixel-perfect recreation of the award-winning Ochi Design website, developed using React.js with mobile responsiveness. This project replicates the unique animation effects and design elements, utilizing Framer Motion for seamless animations and Locomotive Scroll for smooth scrolling with dynamic page speed control. A standout feature includes an interactive "eye" component that tracks the cursor’s movement for enhanced user engagement. This project highlights my expertise in React.js, animation libraries like Framer Motion, and creating immersive, interactive web experiences.`,
    icons: [
      "icons/reactIcon.png",
      "icons/tailwindIcon.png",
      "icons/gsapIcon.png",
      "icons/motionIcon.png",
    ],
  },
  {
    id: 6,
    title: "VirtualR",
    name: "VirtualR",
    para: "Modern React site with Tailwind CSS.",
    git: "https://github.com/Sankalp-2003/VirtualR",
    link: "https://virtualr-sankalp-2003.netlify.app/",
    img: "/VirtualR.png",
    desc: ` A modern, fully responsive website built from scratch using React and Tailwind CSS. The site features a sleek, responsive Navbar with a mobile drawer for easy navigation. It includes a visually striking Hero section with gradient text, providing a modern aesthetic. Integrated video elements play on autoplay and loop to enhance user engagement. The site also features a clean UI for displaying product features, a pricing card section offering three plans, as well as testimonials and a footer—all styled using Tailwind CSS. This project demonstrates my skills in responsive design, React development, and creating modern, user-friendly interfaces with Tailwind CSS.`,
    icons: ["icons/reactIcon.png", "icons/tailwindIcon.png"],
  },
];
