export const SKILLS = [
  {
    id: 1,
    title: "JavaScript",
    percentage: 90,
    icon: "icons/jsIcon.png",
    xl: -700,
    yl: -270,
    xs: -290,
    ys: -520,
  },
  {
    id: 2,
    title: "TypeScript",
    percentage: 75,
    icon: "icons/tsIcon.png",
    xl: -500,
    yl: -200,
    xs: -200,
    ys: -380,
  },
  {
    id: 3,
    title: "React JS",
    percentage: 90,
    icon: "icons/reactIcon.png",
    xl: 600,
    yl: -270,
    xs: 190,
    ys: -530,
  },
  {
    id: 4,
    title: "Angular",
    percentage: 70,
    icon: "icons/angularIcon.png",
    xl: 400,
    yl: -200,
    xs: 90,
    ys: -380,
  },
  {
    id: 5,
    title: "Sass/Scss",
    percentage: 80,
    icon: "icons/sassIcon.png",
    xl: 400,
    yl: 90,
    xs: 90,
    ys: 270,
  },
  {
    id: 6,
    title: "Tailwind Css",
    percentage: 80,
    icon: "icons/tailwindIcon.png",
    xl: 600,
    yl: 170,
    xs: 190,
    ys: 430,
  },
  {
    id: 7,
    title: "HTML",
    percentage: 90,
    icon: "icons/htmlIcon.png",
    xl: -500,
    yl: 90,
    xs: -200,
    ys: 270,
  },
  {
    id: 8,
    title: "CSS",
    percentage: 90,
    icon: "icons/cssIcon.png",
    xl: -700,
    yl: 170,
    xs: -290,
    ys: 430,
  },
  {
    id: 9,
    title: "Bootstrap",
    percentage: 85,
    icon: "icons/bootstrapIcon.png",
    xl: -650,
    yl: -50,
    xs: -290,
    ys: -55,
  },
  {
    id: 10,
    title: "Redux Tool Kit",
    percentage: 80,
    icon: "icons/reduxIcon.png",
    xl: 550,
    yl: -50,
    xs: 190,
    ys: -55,
  },
  {
    id: 11,
    title: "NPM",
    percentage: 80,
    icon: "icons/npmIcon.png",
    xl: -50,
    yl: -250,
    xs: -50,
    ys: -480,
  },
  {
    id: 12,
    title: "Git & Github",
    percentage: 80,
    icon: "icons/gitIcon.png",
    xl: -50,
    yl: 150,
    xs: -50,
    ys: 370,
  },
  {
    id: 13,
    title: "NodeJs",
    percentage: 80,
    icon: "icons/nodejsIcon.png",
    xl: 280,
    yl: -50,
    xs: -50,
    ys: -280,
  },
  {
    id: 14,
    title: "ExpressJs",
    percentage: 80,
    icon: "icons/expressIcon.png",
    xl: 150,
    yl: 90,
    xs: -50,
    ys: 170,
  },
  {
    id: 15,
    title: "MongoDB",
    percentage: 80,
    icon: "icons/mongodbIcon.png",
    xl: 150,
    yl: -200,
    xs: -200,
    ys: 70,
  },
  {
    id: 16,
    title: "Postman",
    percentage: 90,
    icon: "icons/postmanIcon.png",
    xl: -380,
    yl: -50,
    xs: 90,
    ys: 70,
  },
  {
    id: 17,
    title: "GSAP",
    percentage: 75,
    icon: "icons/gsapIcon.png",
    xl: -250,
    yl: -200,
    xs: 90,
    ys: -180,
  },
  {
    id: 18,
    title: "Framer Motion",
    percentage: 80,
    icon: "icons/motionIcon.png",
    xl: -250,
    yl: 90,
    xs: -200,
    ys: -180,
  },
];
