export const SKILLS = [
  {
    id: 1,
    title: "JavaScript",
    percentage: 90,
    icon: "icons/jsIcon.png",
    xl: -350,
    yl: -270,
    xs: -290,
    ys: -260,
    description:
      "I have a strong command of JavaScript, from the fundamentals to advanced concepts. Over the years, I've created numerous front-end projects utilizing JavaScript, which has allowed me to solidify my understanding of the language. I am well-versed in core JavaScript features like closures, asynchronous programming (promises, async/await), event handling, and DOM manipulation. Additionally, I am familiar with ES6+ features, such as arrow functions, destructuring, and modules. My experience in using JavaScript for building dynamic, interactive web applications has helped me craft seamless user experiences on the front-end.",
  },
  {
    id: 2,
    title: "TypeScript",
    percentage: 75,
    icon: "icons/tsIcon.png",
    xl: -210,
    yl: -200,
    xs: -180,
    ys: -170,
    description:
      "I learned TypeScript during my internship and actively took the initiative to explore and deepen my understanding of the language. I used TypeScript in several of my Angular projects, which helped me appreciate its benefits in enhancing code maintainability, readability, and scalability. I am comfortable with key TypeScript features like static typing, interfaces, generics, and type inference. My experience using TypeScript has made me more proficient in writing robust, error-free code while improving collaboration and reducing debugging time in large-scale front-end applications.",
  },
  {
    id: 3,
    title: "React JS",
    percentage: 90,
    icon: "icons/reactIcon.png",
    xl: 250,
    yl: -270,
    xs: 180,
    ys: -260,
    description:
      "React is one of my favorite JavaScript libraries, and I have a solid understanding of its core concepts. Over time, I’ve built many projects using React, which has helped me refine my skills in creating dynamic, responsive, and efficient user interfaces. I am comfortable with essential React features like components, props, state management, and lifecycle methods. Additionally, I have experience working with React hooks and functional components, which allow for cleaner and more modular code. My hands-on experience with React has made me confident in building scalable and performant applications for the web.",
  },
  {
    id: 4,
    title: "Angular",
    percentage: 70,
    icon: "icons/angularIcon.png",
    xl: 100,
    yl: -200,
    xs: 80,
    ys: -170,
    description:
      "I learned Angular during my internship and applied my knowledge to create dynamic and feature-rich web applications. Angular’s powerful features like two-way data binding, dependency injection, and modular architecture allowed me to build scalable and maintainable projects. I used Angular to develop the Paperless Invites website, where I implemented various interactive components, dynamic forms, and routing. My hands-on experience with Angular has helped me understand how to structure and develop large-scale applications effectively while maintaining high performance and good code quality.",
  },
  {
    id: 5,
    title: "Sass/Scss",
    percentage: 80,
    icon: "icons/sassIcon.png",
    xl: 100,
    yl: 90,
    xs: 80,
    ys: 60,
    description:
      "Sass is one of my favorite CSS preprocessors, and I’ve used it in multiple projects to write cleaner, more maintainable styles with features like variables, nesting, and mixins. It improves the scalability and organization of CSS in large applications.",
  },
  {
    id: 6,
    title: "Tailwind Css",
    percentage: 70,
    icon: "icons/tailwindIcon.png",
    xl: 250,
    yl: 170,
    xs: 180,
    ys: 150,
    description:
      "I’ve used Tailwind CSS in multiple React projects, enabling rapid UI development with utility-first classes. It allows for custom designs without writing custom CSS, helping me create responsive and visually appealing layouts quickly.",
  },
  {
    id: 7,
    title: "HTML",
    percentage: 90,
    icon: "icons/htmlIcon.png",
    xl: -210,
    yl: 90,
    xs: -180,
    ys: 60,
    description:
      "I have a solid understanding of HTML, the foundation of web development. I use it to structure web pages, ensuring accessibility and responsiveness, and creating semantic, well-organized content for both users and search engines.",
  },
  {
    id: 8,
    title: "CSS",
    percentage: 90,
    icon: "icons/cssIcon.png",
    xl: -350,
    yl: 170,
    xs: -290,
    ys: 150,
    description:
      "I have strong knowledge and hands-on experience with CSS, specializing in creating responsive web pages. I’m skilled in layout techniques like Flexbox, ensuring cross-browser compatibility and smooth user experiences.",
  },
  {
    id: 9,
    title: "Bootstrap",
    percentage: 85,
    icon: "icons/bootstrapIcon.png",
    xl: -300,
    yl: -50,
    xs: -260,
    ys: -55,
    description:
      "I have experience using Bootstrap, though I prefer leveraging my CSS skills to create custom designs. However, when needed and to save time, I use Bootstrap for rapid development and responsive layouts.",
  },
  {
    id: 10,
    title: "Redux Tool Kit",
    percentage: 80,
    icon: "icons/reduxIcon.png",
    xl: 200,
    yl: -50,
    xs: 160,
    ys: -55,
    description:
      "I have hands-on experience with Redux for state management in React applications, ensuring predictable state transitions and efficient data flow across components. I’ve used Redux in multiple projects to manage complex state logic effectively.",
  },
  {
    id: 11,
    title: "NPM",
    percentage: 80,
    icon: "icons/npmIcon.png",
    xl: -50,
    yl: -250,
    xs: -50,
    ys: -240,
    description:
      "I am proficient in using NPM for managing packages and dependencies in my projects. I use it to install libraries, manage versions, and automate tasks, ensuring smooth development workflows.",
  },
  {
    id: 12,
    title: "Git & Github",
    percentage: 80,
    icon: "icons/gitIcon.png",
    xl: -50,
    yl: 150,
    xs: -50,
    ys: 130,
    description:
      "I am skilled in using Git for version control and GitHub for collaborating on projects. I frequently use Git for tracking changes, branching, and merging code, ensuring efficient project management and team collaboration.",
  },
];
